const carddeck = [{
    imglink: "2_of_clubs.png",
    value: 2 
}, {
    imglink: "3_of_clubs.png",
    value: 3
}, {
    imglink: "4_of_clubs.png",
    value: 4
}, {
    imglink: "5_of_clubs.png",
    value: 5
}, {
    imglink: "6_of_clubs.png",
    value: 6
}, {
    imglink: "7_of_clubs.png",
    value: 7
}, {
    imglink: "8_of_clubs.png",
    value: 8
}, {
    imglink: "9_of_clubs.png",
    value: 9
}, {
    imglink: "10_of_clubs.png",
    value: 10
}, {
    imglink: "jack_of_clubs2.png",
    value: 10
}, {
    imglink: "queen_of_clubs2.png",
    value: 10
}, {
    imglink: "king_of_clubs2.png",
    value: 10
}, {
    imglink: "ace_of_clubs.png",
    value: 11
},{
    imglink: "2_of_diamonds.png",
    value: 2
}, {
    imglink: "3_of_diamonds.png",
    value: 3
}, {
    imglink: "4_of_diamonds.png",
    value: 4
}, {
    imglink: "5_of_diamonds.png",
    value: 5
}, {
    imglink: "6_of_diamonds.png",
    value: 6
}, {
    imglink: "7_of_diamonds.png",
    value: 7
}, {
    imglink: "8_of_diamonds.png",
    value: 8
}, {
    imglink: "9_of_diamonds.png",
    value: 9
}, {
    imglink: "10_of_diamonds.png",
    value: 10
}, {
    imglink: "jack_of_diamonds2.png",
    value: 10
}, {
    imglink: "queen_of_diamonds2.png",
    value: 10
}, {
    imglink: "king_of_diamonds2.png",
    value: 10
}, {
    imglink: "ace_of_diamonds.png",
    value: 11
},{
    imglink: "2_of_hearts.png",
    value: 2
}, {
    imglink: "3_of_hearts.png",
    value: 3
}, {
    imglink: "4_of_hearts.png",
    value: 4
}, {
    imglink: "5_of_hearts.png",
    value: 5
}, {
    imglink: "6_of_hearts.png",
    value: 6
}, {
    imglink: "7_of_hearts.png",
    value: 7
}, {
    imglink: "8_of_hearts.png",
    value: 8
}, {
    imglink: "9_of_hearts.png",
    value: 9
}, {
    imglink: "10_of_hearts.png",
    value: 10
}, {
    imglink: "jack_of_hearts2.png",
    value: 10
}, {
    imglink: "queen_of_hearts2.png",
    value: 10
}, {
    imglink: "king_of_hearts2.png",
    value: 10
}, {
    imglink: "ace_of_hearts.png",
    value: 11
},{
    imglink: "2_of_spades.png",
    value: 2
}, {
    imglink: "3_of_spades.png",
    value: 3
}, {
    imglink: "4_of_spades.png",
    value: 4
}, {
    imglink: "5_of_spades.png",
    value: 5
}, {
    imglink: "6_of_spades.png",
    value: 6
}, {
    imglink: "7_of_spades.png",
    value: 7
}, {
    imglink: "8_of_spades.png",
    value: 8
}, {
    imglink: "9_of_spades.png",
    value: 9
}, {
    imglink: "10_of_spades.png",
    value: 10
}, {
    imglink: "jack_of_spades2.png",
    value: 10
}, {
    imglink: "queen_of_spades2.png",
    value: 10
}, {
    imglink: "king_of_spades2.png",
    value: 10
}, {
    imglink: "ace_of_spades.png",
    value: 11
}];


exports.carddeck = carddeck;